import React, { useState, useEffect, useRef } from 'react';
import LogoBar from './components/LogoBar';
import DropdownMenu from './components/DropdownMenu';
import GenerateSongButton from './components/GenerateSongButton';
import RefreshInputMenusButton from './components/RefreshInputMenusButton';
import ResubmitPromptButton from './components/ResubmitPromptButton';
import MusicTechLoader from './components/MusicTechLoader';
import AudioVisualizer from './components/AudioVisualizer';
import './App.css';

const App: React.FC = () => {
  const [mood, setMood] = useState<string>('');
  const [tempo, setTempo] = useState<string>('');
  const [genre, setGenre] = useState<string>('');
  const [songUrl, setSongUrl] = useState<string>('');
  const [songName, setSongName] = useState<string>('');
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [songGenerated, setSongGenerated] = useState<boolean>(false);
  const [showScrollTop, setShowScrollTop] = useState<boolean>(false);

  const landingPageRef = useRef<HTMLDivElement>(null);
  const audioRef = useRef<HTMLAudioElement>(null);
  const loadingRef = useRef<HTMLElement>(null);
  const makeGrooveRef = useRef<HTMLElement>(null);
  const contactRef = useRef<HTMLElement>(null);

  useEffect(() => {
    if (audioRef.current) {
      audioRef.current.load();
    }
  }, [songUrl]);

  useEffect(() => {
    if (isLoading && loadingRef.current) {
      const header = document.getElementById('title');
      const headerHeight = header ? header.offsetHeight : 0;
      const top = loadingRef.current.getBoundingClientRect().top + window.scrollY - headerHeight;
      window.scrollTo({ top, behavior: 'smooth' });
    }
  }, [isLoading]);

  useEffect(() => {
    if (landingPageRef.current) {
      const landingPage = landingPageRef.current;
      const logoBar = landingPage.querySelector('.logo-container');
      const landingPageText = landingPage.querySelector('.landing-page-text');

      if (logoBar && landingPageText) {
        const totalHeight = logoBar.clientHeight + landingPageText.clientHeight;
        landingPage.style.height = `${totalHeight}px`;
      }
    }
  }, []);

  const scrollFunction = () => {
    const scrolled = document.body.scrollTop > 50 || document.documentElement.scrollTop > 50;
    const title: HTMLElement | null = document.getElementById('title');
    if (title) {
      if (scrolled) {
        title.style.fontSize = "2.5rem";
        title.style.height = '10vh';
      } else {
        title.style.fontSize = "7rem";
        title.style.height = '30vh';
      }
    }
    setShowScrollTop(document.documentElement.scrollTop > 300);
  };

// useEffect added to handle correct title display on page load and scroll
  useEffect(() => {
    const title = document.getElementById('title');

    // Disable transitions initially
    if (title) {
      title.classList.add('no-transition');
    }

    // Initialize title size on page load
    scrollFunction();

    // Re-enable transitions after initial load
    setTimeout(() => {
      if (title) {
        title.classList.remove('no-transition');
      }
    }, 100); // Adjust timing as necessary

    // Attach the scroll event listener
    window.addEventListener('scroll', scrollFunction);

    // Cleanup the event listener on component unmount
    return () => {
      window.removeEventListener('scroll', scrollFunction);
    };
  }, []);

  const scrollToContact = (event: React.MouseEvent<HTMLAnchorElement, MouseEvent>) => {
    event.preventDefault();
    const header = document.getElementById('title');
    const headerHeight = header ? header.offsetHeight : 0;
    const top = (contactRef.current?.getBoundingClientRect().top ?? 0) + window.scrollY - headerHeight;
    window.scrollTo({ top, behavior: 'smooth' });
  };

  return (
    <div>
      <div ref={landingPageRef} className="landing-page">
        <video autoPlay muted loop className="background-video">
          <source src="/assets/musicnotes.mp4" type="video/mp4" />
        </video>
        <section className='landing-page-text'>
          <h1 id='title'>AutomatedGroove</h1>
          <div className='intro'>
            <pre className='sm-text'>
              {'High-quality license- and royalty-free grooves\nfor all your music needs'}
            </pre>
            <p className='md-text'>Generated by AI</p>
            <p className='lg-text'>Certified groovy by you.</p>
            <br />
            <br />
            <p className='logo-bar-text'>Use with your favorite platforms. No restrictions. Ever.</p>
            <LogoBar />
          </div>
        </section>
      </div>
      <div className='content'>
        { (!songGenerated && !isLoading) &&
          <section className='make-groove' ref={makeGrooveRef}>
            <h2>Are you ready? Let's groove.</h2>
            <div className='dropdown-container'>
              <DropdownMenu placeholder="Genre" options={["rock", "pop", "edm", "hiphop", "country"]} selectedOption={genre} onSelect={setGenre} />
              <DropdownMenu placeholder="Tempo" options={["slow", "medium", "fast"]} selectedOption={tempo} onSelect={setTempo} />
              <DropdownMenu placeholder="Mood" options={["happy", "sad", "angry", "romantic", "euphoric"]} selectedOption={mood} onSelect={setMood} />
            </div>
            <div>
              <GenerateSongButton
                genre={genre}
                mood={mood}
                tempo={tempo}
                setSongUrl={setSongUrl}
                setSongName={setSongName}
                isLoading={isLoading}
                setIsLoading={setIsLoading}
                setSongGenerated={setSongGenerated}/>
            </div>
          </section>
        }
        {isLoading &&
          <section ref={loadingRef}>
              <h2>Finding the groove...</h2>
              <div>
                <MusicTechLoader />
              </div>
          </section>
        }
        { songGenerated &&
          <>
            <section className='get-groove-flex'>
              <h2>Get into your groove!</h2>
              <div>
                <AudioVisualizer audioRef={audioRef} />
                <audio ref={audioRef} src={songUrl} controls crossOrigin="anonymous" data-testid="audio-player"/>
                <div>{songName}</div>
              </div>
            </section>
            <section>
              <div>
                <div className='groove-again'>
                  <h2>Here we groove again!</h2>
                  <ResubmitPromptButton
                    genre={genre}
                    mood={mood}
                    tempo={tempo}
                    setSongUrl={setSongUrl}
                    setSongName={setSongName}
                    setIsLoading={setIsLoading}
                    setSongGenerated={setSongGenerated}/>
                  <RefreshInputMenusButton
                    setMood={setMood}
                    setTempo={setTempo}
                    setGenre={setGenre}
                    setSongUrl={setSongUrl}
                    setSongName={setSongName}
                    setIsLoading={setIsLoading}
                    setSongGenerated={setSongGenerated}
                    onScrollToForm={() => {
                      setTimeout(() => {
                        const header = document.getElementById('title');
                        const headerHeight = header ? header.offsetHeight : 0;
                        const top = (makeGrooveRef.current?.getBoundingClientRect().top ?? 0) + window.scrollY - headerHeight;
                        window.scrollTo({ top, behavior: 'smooth' });
                      }, 50);
                    }}/>
                </div>
              </div>
            </section>
          </>
        }
        <section>
          <div className="faq">
            <h2>FAQs</h2>
            <ul>
              <li>How long are the generated songs?</li>
              <ul className='answer'><li>30 seconds.</li></ul>
              <li>Can I download my song?</li>
              <ul className='answer'><li>Yes. Once a song has loaded, click the three vertical dots on the audio player for the download option.</li></ul>
              <li>Is this royalty-free music?</li>
              <ul className='answer'><li>Yes.</li></ul>
              <li>Do I need to credit AutomatedGroove?</li>
              <ul className='answer'><li>No.</li></ul>
            </ul>
            <p>
              Have a different question? Groovy. <a href="#" onClick={(event) => scrollToContact(event)} style={{ fontWeight: 'bold' }}>Get in touch.</a>
            </p>

          </div>
        </section>
        <section ref={contactRef}>
          <div>
            <h2>The AutomatedGroove Group</h2>
            <div className="contact-container">
              <div>
                <img src="/assets/linkedin_kit.png" className="contact"></img>
                <h3>Kit</h3>
                <p>(She/Her)</p>
              </div>
              <div>
                <img src="/assets/linkedin_sunny.jpeg" className="contact"></img>
                <h3>Sunny</h3>
                <p>(She/Her)</p>
              </div>
              <div>
                <img src="/assets/linkedin_anika.jpeg" className="contact"></img>
                <h3>Anika</h3>
                <p>(She/Her)</p>
                <a href='http://www.linkedin.com/in/anika-stephen-wilbur' target="_blank">LinkedIn</a>
              </div>
              <div>
                <img src="/assets/linkedin_shelby.jpeg" className="contact"></img>
                <h3>Shelby</h3>
                <p>(She/They)</p>
              </div>
            </div>
          </div>
        </section>
      </div>
      {showScrollTop && (
        <button
          className="scroll-to-top"
          onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
          aria-label="Scroll to top"
        >
          <span style={{ display: 'inline-block', transform: 'translateY(-2px)' }}>&#9650;</span>
        </button>
      )}
      <hr></hr>
      <footer className="footer">
        <p>&copy; AutomatedGroove v2. All rights reserved.</p>
      </footer>
    </div>
  );
};

export default App;
